# Generated by Django 6.0.4 on 2026-04-22 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BEX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bex', models.CharField(max_length=50, unique=True)),
                ('type_bex', models.CharField(choices=[('LOCAL', 'Local'), ('MARITIME', 'Maritime'), ('AERIEN', 'Aérien'), ('HORS_BEX', 'Hors BEX')], max_length=20)),
                ('fournisseur', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('POINTE', 'Pointé'), ('VALIDE', 'Validé'), ('RECEPTIONNE', 'Réceptionné'), ('DEDOUANE', 'Dédouané'), ('PRET_RECEPTION', 'Prêt pour réception')], default='EN_ATTENTE', max_length=25)),
                ('date_pointage_pharmacien', models.DateTimeField(blank=True, null=True)),
                ('date_reception_rsi', models.DateTimeField(blank=True, null=True)),
                ('agent_createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bex_crees', to=settings.AUTH_USER_MODEL)),
                ('pharmacien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bex_pointes', to=settings.AUTH_USER_MODEL)),
                ('rsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bex_receptionnes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BEX',
                'verbose_name_plural': 'BEX',
            },
        ),
        migrations.CreateModel(
            name='ADI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_adi', models.CharField(max_length=50)),
                ('bex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adis', to='transit.bex')),
            ],
            options={
                'verbose_name': 'ADI',
                'verbose_name_plural': 'ADIs',
            },
        ),
        migrations.CreateModel(
            name='CCPQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ccpq', models.CharField(max_length=50)),
                ('bex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccpqs', to='transit.bex')),
            ],
            options={
                'verbose_name': 'CCPQ',
                'verbose_name_plural': 'CCPQ',
            },
        ),
        migrations.CreateModel(
            name='Conteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conteneur', models.CharField(max_length=50)),
                ('bex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteneurs', to='transit.bex')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='transit/documents/')),
                ('type_document', models.CharField(choices=[('FACTURE', 'Facture'), ('ADI', 'ADI'), ('CCPQ', 'CCPQ'), ('REC165', 'REC165'), ('LIQUIDATION', 'Liquidation douanière'), ('AUTRE', 'Autre')], max_length=50)),
                ('format', models.CharField(choices=[('PHYSIQUE', 'Physique'), ('NUMERIQUE', 'Numérique')], default='NUMERIQUE', max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('agent_createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transit.bex')),
                ('conteneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_conteneur', to='transit.conteneur')),
            ],
        ),
    ]
