# Generated by Django 6.0.4 on 2026-04-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ccpq',
            options={},
        ),
        migrations.AddField(
            model_name='bex',
            name='date_enlevement_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bex',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bex',
            name='statut_douanier',
            field=models.CharField(default='En attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='bex',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('POINTE', 'Pointé'), ('VALIDE', 'Validé'), ('RECEPTIONNE', 'Réceptionné'), ('DEDOUANE', 'Dédouané'), ('PRET_RECEPTION', 'Prêt pour réception'), ('BLOQUE', 'Bloqué')], default='EN_ATTENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='bex',
            name='type_bex',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('MARITIME', 'Maritime'), ('AERIEN', 'Aérien'), ('HORS_BEX', 'Hors BEX')], default='MARITIME', max_length=20),
        ),
        migrations.CreateModel(
            name='BEXItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conteneur', models.CharField(max_length=50)),
                ('designation_produit', models.TextField()),
                ('quantite', models.PositiveIntegerField()),
                ('facture_fcfa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transit.bex')),
            ],
        ),
    ]
