# Generated by Django 6.0.4 on 2026-04-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_alter_adi_options_alter_ccpq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adi',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adi',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adi',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adi',
            name='organisme_emetteur',
            field=models.CharField(default='ANRP', max_length=100),
        ),
        migrations.AddField(
            model_name='adi',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adi',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='ccpq',
            name='date_depot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ccpq',
            name='date_resultat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ccpq',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ccpq',
            name='resultat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ccpq',
            name='statut',
            field=models.CharField(choices=[('NON_DEMARRE', 'Non démarré'), ('EN_ANALYSE', 'En analyse'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='NON_DEMARRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='adi',
            name='bex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adis', to='transit.bex'),
        ),
        migrations.AlterField(
            model_name='adi',
            name='numero_adi',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ccpq',
            name='bex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccpqs', to='transit.bex'),
        ),
        migrations.AlterField(
            model_name='ccpq',
            name='numero_ccpq',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
