# Generated by Django 6.0.4 on 2026-05-06 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_adi_date_adi_fournisseur_adi_observations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adi',
            name='agent_createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adis_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ccpq',
            name='agent_createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccpqs_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
