# Generated by Django 6.0.5 on 2026-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_adi_agent_createur_ccpq_agent_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='adi',
            name='asi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adi',
            name='cout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='adi',
            name='date_depot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adi',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adi',
            name='factures',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adi',
            name='nb_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adi',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adi',
            name='date',
            field=models.DateField(blank=True, help_text='Ancien champ date', null=True),
        ),
    ]
