# Generated by Django 6.0.5 on 2026-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_adi_asi_adi_cout_adi_date_depot_adi_date_reception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccpq',
            name='fob_euro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ccpq',
            name='fob_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ccpq',
            name='numero_sylvie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
