# Generated by Django 6.0.5 on 2026-05-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0006_ccpq_fob_euro_ccpq_fob_fcfa_ccpq_numero_sylvie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bex',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bex',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bexitem',
            name='adi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bexitem',
            name='asi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bexitem',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bexitem',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bexitem',
            name='numero_sylvie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bexitem',
            name='statut_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bexitem',
            name='designation_produit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bexitem',
            name='facture_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bexitem',
            name='numero_conteneur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bexitem',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
