# Generated by Django 6.0.5 on 2026-06-26 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0007_bex_date_arrivee_bex_date_depart_bexitem_adi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True, verbose_name='Référence des factures ou pro-forma')),
                ('nombre_item', models.PositiveIntegerField(default=0, verbose_name="Nombre d'item")),
                ('quantite_produits', models.PositiveIntegerField(default=0, verbose_name='Quantités de produits')),
                ('items_asi', models.PositiveIntegerField(default=0, verbose_name='Items ASI')),
                ('items_adi', models.PositiveIntegerField(default=0, verbose_name='Items ADI')),
                ('cout_facture', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Coût/facture (EURO)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agent_createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture ou Pro-forma',
                'verbose_name_plural': 'Factures et Pro-formas',
            },
        ),
    ]
